### ISSUE TITLE
Feature request: Add an RSS feed to the KlipTok blog

### ISSUE THREAD

**Issue by alvinashcraft** [csharpfritz/KlipTok.Blog#3]
It would be great to allow fans to follow the blog in their favorite RSS readers.

**Comment by csharpfritz** [comment]
Finishing and deploying on stream June 28, 2022

**Comment by csharpfritz** [comment]
Completed and deployed - https://kliptok.com/blog/rss.xml

**Comment by alvinashcraft** [comment]
Awesome! Thanks, Jeff.
